### ISSUE TITLE
[BE] GET project/:project-id/version/:oldversion-id/:newversion-id/pages/:page-id (2)

### ISSUE THREAD

**Issue by tjd985** [Figci/Figci-Plugin-Server#5]
## 이슈 사항
(2) 분석 로직 결과를 DB에 저장하고 사용자에게 결과를 전달한다.

<br />

## API Endpoint
GET /`project/:project-id/verson/:oldverson-id/:newverson-id/pages/:page-id`

<br/>

## Todo 리스트
- [ ] 분석 로직을 수행 결과를 몽고 DB  `Difference` 스키마에 저장한다.
- [ ] 결과 분석과 DB 입력이 성공한 경우 UI 로 성공 코드를 전달한다.
- [ ] 플러그인 API에 변경 감지된 노드 위치에 🟥 표시 렌더링 요청한다.

<br />

<h2>응답(Response)</h2>
<h3>응답 상태 코드</h3>

Status Code | Description
-- | --
200 | OK
400 | Bad Request
500 | Internal Server Error

<h3>성공 시</h3>
<pre><code class="language-json">{
  &quot;Result&quot;: &quot;success&quot;,
  &quot;message&quot;: &quot;OK&quot;
}
</code></pre>
<h3>클라이언트 오류 시</h3>
<pre><code class="language-json">{
  &quot;result&quot;: &quot;error&quot;,
  &quot;error&quot;: {
    &quot;message&quot;: &quot;Bad Request&quot;,
  } 	
}
</code></pre>
<h3>서버 오류 시</h3>
<pre><code class="language-json">{
  &quot;result&quot;: &quot;error&quot;,
  &quot;error&quot;: {
    &quot;message&quot;: &quot;Internal Server Error&quot;,
  } 	
}
</code></pre>
