### ISSUE TITLE
[BE] GET project/:project-id/version/:oldversion-id/:newversion-id/pages/:page-id (3)

### ISSUE THREAD

**Issue by tjd985** [Figci/Figci-Plugin-Server#6]
## 이슈 사항
(3) 변경 감지된 노드의 영역에 🟥  플러그인 API 렌더링을 요청한다.

<br />

## Todo 리스트
- [ ]  분석 결과 존재 - `difference` 에서 특정 페이지의 노드 정보를 가져온다.
- [ ]  분석 결과  미 존재 - 분석 로직 수행후 nodeID 와 position 을 가져온다.
- [ ]  플러그인 API에 변경 감지된 노드 위치에 🟥 표시 렌더링 요청한다.

<br />

<h2>응답(Response)</h2>
<h3>응답 상태 코드</h3>

Status Code | Description
-- | --
200 | OK
400 | Bad Request
500 | Internal Server Error
