### ISSUE TITLE
[BE] DELETE project/:project-id/version/:oldversion-id/:newversion-id/pages/:page-id

### ISSUE THREAD

**Issue by tjd985** [Figci/Figci-Plugin-Server#7]
## 이슈 사항
- `다른 버전 비교`클릭 , `다른 페이지 비교` 클릭, 플러그인 종료 시
플러그인으로 부터 만들어진 🟩 Rect 요소를 모두 삭제한다.

### 🟩 Rect 노드 삭제 로직

- UI로 부터 전달받은 각  🟩 Rect 노드의 id를 사용해서 삭제할 노드를 특정 짓는다.
- 삭제할 노드를 대상으로 `remove()`  메서드를 실행해서 캔버스상에서 삭제 한다.

<br />

# API Endpoint
DELETE /`project/:project-id/verson/:oldverson-id/:newverson-id/pages/:page-id`

<br/>

## Todo 리스트
- [ ]  `다른 버전 비교`클릭 , `다른 페이지 비교` 클릭, 플러그인 종료 이벤트 발생시 호출한다.
- [ ]  UI로 부터 전달받은 각  🟩 Rect 노드의 id를 사용해서 삭제할 노드를 특정 짓는다.
- [ ]  삭제할 노드를 대상으로 `remove()`  메서드를 실행해서 캔버스상에서 삭제 한다.

<br />

<h2>응답(Response)</h2>
<h3>응답 상태 코드</h3>

Status Code | Description
-- | --
200 | OK
401 | Unauthorized
500 | Internal Server Error

### 성공 시

```json
{
  "result": "success",
  "statusCode": 200,
}
```

### 서버 오류 시

```json
{
  "result": "error",
  "error": {
    "message": "Bad Request",
  } 	
}
```

### 서버 오류 시

```json
{
  "result": "error",
  "error": {
    "message": "Internal Server Error",
  } 	
}
```
