### ISSUE TITLE
[일반] 프로젝트 발표준비

### ISSUE THREAD

**Issue by tjd985** [Figci/Figci-Plugin-Server#9]
## 이슈 사항
웹사이트 배포 후 프로젝트 배경, 프로젝트 설명, 기술 챌린지 등 프로젝트에 대한 내용과 함께 발표를 준비합니다.

<br />

## Todo 리스트
- [ ]  발표 준비를 위한 웹사이트 테스트를 진행합니다.
- [ ]  테스트 후, 시연할 플로우를 정리합니다.
- [ ]  발표하기 위한 내용을 정리합니다.
- [ ]  발표하기 위한 내용을 정리하기 위해 발표 자료를 준비합니다.

<br />
